name = "小雨信通"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"
description = "小雨信通简单描述"
homepage = "https://github.com/wowchemy/starter-hugo-research-group"
demosite = "https://research-group.netlify.app/"
tags = ["responsive",
        "clean",
        "company",
        "events"
        ]

[author]
  name = "xyxtkj"
  homepage = "https://xyxtkj.com"
